name: Deploy Gradio to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: |
          pip install -r requirements.txt

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/chitsanfei/review-screening-analyzer main --force
